version: "3.9"

services:
  api:
    build: ./api
    container_name: pulso_api
    ports:
      - "8080:8080"
    environment:
      - FEATURE_STORE_URI=postgresql://user:pass@db:5432/features
      - REDIS_URI=redis://redis:6379/0
    depends_on:
      - db
      - redis

  ingest:
    build: ./ingest
    container_name: pulso_ingest
    environment:
      - QUEUE_URI=redis://redis:6379/0
      - DB_URI=postgresql://user:pass@db:5432/features
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: pulso_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:16
    container_name: pulso_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: features
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pulso_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
